### ISSUE TITLE
Typo in Import Statement for "Layout" Component on Line 4 of app.jsx

### ISSUE THREAD

**Issue by adarshswaminath** [arshalabbas/Quiz-App#1]
I noticed a typo in the import statement on line 4 of the app.jsx file in client. The issue is with the import statement for the "Layout" component. It is currently imported as
```
import Layout from "./layout";
```
However, it should be:
```
import Layout from "./Layout";
```

**Comment by arshalabbas** [comment]
Oops! I've fixed that. Isn't JS case-sensitive on file path? Cuz it's working fine tho 😂
Btw thanks 💖

**Comment by adarshswaminath** [comment]
No, JavaScript (JS) itself is not case sensitive when it comes to file paths

**Comment by adarshswaminath** [comment]
No, JavaScript (JS) itself is not case sensitive when it comes to file paths
